apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanas.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: Grafana
    listKind: GrafanaList
    plural: grafanas
    singular: grafana
  scope: Namespaced
  subresources:
    status: { }
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: [ "spec" ]
      properties:
        spec:
          properties:
            containers:
              type: array
              items:
                type: object
                description: Additional container to add to the grafana pod
            secrets:
              type: array
              items:
                type: string
                description: Secret to be mounted as volume into the grafana deployment
            configMaps:
              type: array
              items:
                type: string
                description: Config map to be mounted as volume into the grafana deployment
            logLevel:
              type: string
              description: Log level of the grafana instance, defaults to info
            adminUser:
              type: string
              description: Default admin user name
            adminPassword:
              type: string
              description: Default admin password
            basicAuth:
              type: boolean
              description: Basic auth enabled
            disableLoginForm:
              type: boolean
              description: Disable login form
            disableSignoutMenu:
              type: boolean
              description: Disable signout menu
            anonymous:
              type: boolean
              description: Anonymous auth enabled
            config:
              type: object
              description: Grafana config
            ingress:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: Create an ingress / route
                ingressClassName:
                  type: string
                  description: Ingress class name
                path:
                  type: string
                  description: Ingress path
                pathType:
                  type: string
                  description: pathType specifies how ingress paths should be matched
                hostname:
                  type: string
                  description: The hostname of the ingress / route
                annotations:
                  type: object
                  description: Additional annotations for the ingress / route
                labels:
                  type: object
                  description: Additional labels for the ingress / route
                targetPort:
                  type: string
                  description: Override port to target in the grafana service
            service:
              type: object
              properties:
                name:
                  type: string
                  description: Override default service name
                ports:
                  type: array
                  description: Override default ports
                  items:
                    type: object
                    description: A port to add to the grafana service
                annotations:
                  type: object
                  description: Additional annotations for the service
                labels:
                  type: object
                  description: Additional labels for the service
                type:
                  type: string
                  description: Service type (NodePort, ClusterIP or LoadBalancer)
            deployment:
              type: object
              properties:
                annotations:
                  type: object
                  description: Additional annotations for the service
                labels:
                  type: object
                  description: Additional labels for the service
                nodeSelector:
                  type: object
                  description: Additional labels for the running grafana pods in a labeled node.
                tolerations:
                  type: array
                  description: Additonal labels for running grafana pods in tained nodes.
                affinity:
                  type: object
                  description: Additonal labels for running grafana pods with affinity properties.
                envFrom:
                  type: array
                  description: Environment variables from Secret or ConfigMap.
                skipCreateAdminAccount:
                  type: boolean
                  description: Disable creating a random admin user
                strategy:
                  description: DeploymentStrategy describes how to replace existing
                    pods with new ones.
                  properties:
                    rollingUpdate:
                      description: 'Rolling update config params. Present only if
                        DeploymentStrategyType = RollingUpdate. --- TODO: Update
                        this to follow our convention for oneOf, whatever we decide
                        it to be.'
                      properties:
                        maxSurge:
                          anyOf:
                          - type: integer
                          - type: string
                          description: 'The maximum number of pods that can be scheduled
                            above the desired number of pods. Value can be an absolute
                            number (ex: 5) or a percentage of desired pods (ex:
                            10%). This can not be 0 if MaxUnavailable is 0. Absolute
                            number is calculated from percentage by rounding up.
                            Defaults to 25%. Example: when this is set to 30%, the
                            new ReplicaSet can be scaled up immediately when the
                            rolling update starts, such that the total number of
                            old and new pods do not exceed 130% of desired pods.
                            Once old pods have been killed, new ReplicaSet can be
                            scaled up further, ensuring that total number of pods
                            running at any time during the update is at most 130%
                            of desired pods.'
                          x-kubernetes-int-or-string: true
                        maxUnavailable:
                          anyOf:
                          - type: integer
                          - type: string
                          description: 'The maximum number of pods that can be unavailable
                            during the update. Value can be an absolute number (ex:
                            5) or a percentage of desired pods (ex: 10%). Absolute
                            number is calculated from percentage by rounding down.
                            This can not be 0 if MaxSurge is 0. Defaults to 25%.
                            Example: when this is set to 30%, the old ReplicaSet
                            can be scaled down to 70% of desired pods immediately
                            when the rolling update starts. Once new pods are ready,
                            old ReplicaSet can be scaled down further, followed
                            by scaling up the new ReplicaSet, ensuring that the
                            total number of pods available at all times during the
                            update is at least 70% of desired pods.'
                          x-kubernetes-int-or-string: true
                      type: object
                    type:
                      description: Type of deployment. Can be "Recreate" or "RollingUpdate".
                        Default is RollingUpdate.
                      type: string
                  type: object
                priorityClassName:
                  type: string
                  description: Pod priority class name
                extraVolumeMounts:
                  type: array
                  description: Extra volumes mounts to be mounted to the grafana deployment
                  items:
                    type: object
                    description: additional volumeMount 
                extraVolumes:
                  type: array
                  description: Extra volumes to be attached to the grafana deployment
                  items:
                    type: object
                    description: additional volume
            serviceAccount:
              type: object
              properties:
                skip:
                  type: boolean
                  description: Disable ServiceAccount creation for grafana
                annotations:
                  type: object
                  description: Additional annotations for the serviceaccount
                labels:
                  type: object
                  description: Additional labels for the serviceaccount
            client:
              type: object
              description: Grafana client settings
            compat:
              type: object
              description: Backwards compatibility switches
            dashboardLabelSelectors:
              type: array
              items:
                type: object
                description: Label selector or match expressions
            jsonnet:
              type: object
              description: Jsonnet library configuration
            livenessProbeSpec:
              type: object
              properties:
                initialDelaySeconds:
                  description: >-
                    Number of seconds after the container has
                    started before liveness probes are initiated. More info:
                    https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
                  format: int32
                  type: integer
                timeoutSeconds:
                  description: Number of seconds after which the probe times out. Defaults to 1 second.
                    Minimum value is 1.
                  format: int32
                  type: integer
                periodSeconds:
                  description: >-
                    How often (in seconds) to perform the probe.
                    Default to 10 seconds. Minimum value is 1.
                  format: int32
                  type: integer
                successThreshold:
                  description: >-
                    Minimum consecutive successes for the probe
                    to be considered successful after having failed. Defaults
                    to 1. Must be 1 for liveness and startup. Minimum value
                    is 1.
                  format: int32
                  type: integer
                failureThreshold:
                  description: >-
                    When a probe fails, Kubernetes will try failureThreshold times before giving up.
                    Giving up in case of liveness probe means restarting the container.
                    In case of readiness probe the Pod will be marked Unready.
                    Defaults to 3. Minimum value is 1.
                  format: int32
                  type: integer
            readinessProbeSpec:
              type: object
              properties:
                initialDelaySeconds:
                  description: >-
                    Number of seconds after the container has
                    started before liveness probes are initiated. More info
                    https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
                  format: int32
                  type: integer
                timeoutSeconds:
                  description: >-
                    Number of seconds after which the probe times out. Defaults to 1 second.
                    Minimum value is 1.
                  format: int32
                  type: integer
                periodSeconds:
                  description: >-
                    How often (in seconds) to perform the probe.
                    Default to 10 seconds. Minimum value is 1.
                  format: int32
                  type: integer
                successThreshold:
                  description: >-
                    Minimum consecutive successes for the probe
                    to be considered successful after having failed. Defaults
                    to 1. Must be 1 for liveness and startup. Minimum value
                    is 1.
                  format: int32
                  type: integer
                failureThreshold:
                  description: >-
                    When a probe fails, Kubernetes will try failureThreshold times before giving up.
                    Giving up in case of liveness probe means restarting the container.
                    In case of readiness probe the Pod will be marked Unready.
                    Defaults to 3. Minimum value is 1.
                  format: int32
                  type: integer
