apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lokis.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: Loki
    listKind: LokiList
    plural: lokis
    singular: loki
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Loki is the Schema for the lokis API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: LokiSpec defines the desired state of Loki
              properties:
                external:
                  description: When set, refer to unmamnaged Loki instance and do not
                    create a managed one
                  properties:
                    url:
                      type: string
                  type: object
              type: object
              livenessProbeSpec:
                type: object
                properties:
                  initialDelaySeconds:
                    description: >-
                      Number of seconds after the container has
                      started before liveness probes are initiated. More info:
                      https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
                    format: int32
                    type: integer
                  timeoutSeconds:
                    description: Number of seconds after which the probe times out. Defaults to 1 second.
                      Minimum value is 1.
                    format: int32
                    type: integer
                  periodSeconds:
                    description: >-
                      How often (in seconds) to perform the probe.
                      Default to 10 seconds. Minimum value is 1.
                    format: int32
                    type: integer
                  successThreshold:
                    description: >-
                      Minimum consecutive successes for the probe
                      to be considered successful after having failed. Defaults
                      to 1. Must be 1 for liveness and startup. Minimum value
                      is 1.
                    format: int32
                    type: integer
                  failureThreshold:
                    description: >-
                      When a probe fails, Kubernetes will try failureThreshold times before giving up.
                      Giving up in case of liveness probe means restarting the container.
                      In case of readiness probe the Pod will be marked Unready.
                      Defaults to 3. Minimum value is 1.
                    format: int32
                    type: integer
              readinessProbeSpec:
                type: object
                properties:
                  initialDelaySeconds:
                    description: >-
                      Number of seconds after the container has
                      started before liveness probes are initiated. More info
                      https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
                    format: int32
                    type: integer
                  timeoutSeconds:
                    description: >-
                      Number of seconds after which the probe times out. Defaults to 1 second.
                      Minimum value is 1.
                    format: int32
                    type: integer
                  periodSeconds:
                    description: >-
                      How often (in seconds) to perform the probe.
                      Default to 10 seconds. Minimum value is 1.
                    format: int32
                    type: integer
                  successThreshold:
                    description: >-
                      Minimum consecutive successes for the probe
                      to be considered successful after having failed. Defaults
                      to 1. Must be 1 for liveness and startup. Minimum value
                      is 1.
                    format: int32
                    type: integer
                  failureThreshold:
                    description: >-
                      When a probe fails, Kubernetes will try failureThreshold times before giving up.
                      Giving up in case of liveness probe means restarting the container.
                      In case of readiness probe the Pod will be marked Unready.
                      Defaults to 3. Minimum value is 1.
                    format: int32
                    type: integer
            status:
              description: LokiStatus defines the observed state of Loki
              properties:
                message:
                  type: string
                phase:
                  type: string
                url:
                  type: string
              required:
                - message
                - phase
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: { }
